import type { ActionDef } from '../types';

/**
 * The verbs of the game — every one of them a real thing you actually do.
 *
 * Tuning notes, so future edits stay coherent:
 *  - A full, well-lived day lands around 200–320 XP. Nothing here is meant to
 *    be farmable; `softCap` is the honest limit past which more stops paying.
 *  - Actions that are *effective* (reviewing, deliberate practice, teaching)
 *    pay better per minute than actions that merely feel productive. The
 *    numbers are an opinion about how to live, not just a score.
 *  - `restores` pays forward into tomorrow's baseline; `strain` is the cost of
 *    burning the candle at both ends. Both are small on purpose.
 */
const defs: ActionDef[] = [
  /* --------------------------------------------------------------- mind */
  {
    id: 'study',
    name: 'Study session',
    emoji: '📘',
    category: 'mind',
    blurb: 'Sit with the material and work.',
    unit: 'minutes',
    xpPerUnit: 0.55,
    attributes: { knowledge: 0.5, focus: 0.2, discipline: 0.1 },
    vitals: { clarity: -0.12, energy: -0.06 },
    keyVital: 'clarity',
    softCap: 150,
    masteryStep: 600,
    tags: ['learning', 'deep'],
    quickAmount: 45,
    strain: 0.01,
  },
  {
    id: 'review',
    name: 'Review & recall',
    emoji: '🔁',
    category: 'mind',
    blurb: 'Go back over what you already learned. The highest-value hour there is.',
    unit: 'minutes',
    xpPerUnit: 0.75,
    attributes: { knowledge: 0.6, focus: 0.25, discipline: 0.2 },
    vitals: { clarity: -0.1 },
    keyVital: 'clarity',
    softCap: 90,
    masteryStep: 400,
    tags: ['learning', 'deep'],
    quickAmount: 25,
  },
  {
    id: 'practice_problems',
    name: 'Practice problems',
    emoji: '✍️',
    category: 'mind',
    blurb: 'Work it out yourself before looking.',
    unit: 'minutes',
    xpPerUnit: 0.72,
    attributes: { knowledge: 0.55, focus: 0.3, discipline: 0.2 },
    vitals: { clarity: -0.14 },
    keyVital: 'clarity',
    softCap: 120,
    masteryStep: 500,
    tags: ['learning', 'deep'],
    quickAmount: 30,
    strain: 0.01,
  },
  {
    id: 'read',
    name: 'Read a book',
    emoji: '📖',
    category: 'mind',
    blurb: 'Anything that is not a feed.',
    unit: 'minutes',
    xpPerUnit: 0.5,
    attributes: { knowledge: 0.4, creativity: 0.15, focus: 0.15 },
    vitals: { clarity: 0.05, spirit: 0.04 },
    keyVital: 'clarity',
    softCap: 120,
    masteryStep: 600,
    tags: ['learning', 'calm'],
    quickAmount: 30,
    restores: 0.01,
  },
  {
    id: 'lecture',
    name: 'Class or lecture',
    emoji: '🏫',
    category: 'mind',
    blurb: 'Showing up counts, even when it is passive.',
    unit: 'minutes',
    xpPerUnit: 0.34,
    attributes: { knowledge: 0.32, discipline: 0.15 },
    vitals: { energy: -0.05, clarity: -0.05 },
    keyVital: 'clarity',
    softCap: 240,
    masteryStep: 900,
    tags: ['learning'],
    quickAmount: 60,
  },
  {
    id: 'language',
    name: 'Language practice',
    emoji: '🗣️',
    category: 'mind',
    blurb: 'Vocabulary, listening, speaking out loud.',
    unit: 'minutes',
    xpPerUnit: 0.58,
    attributes: { knowledge: 0.42, creativity: 0.12, discipline: 0.15 },
    vitals: { clarity: -0.06 },
    keyVital: 'clarity',
    softCap: 60,
    masteryStep: 300,
    tags: ['learning'],
    quickAmount: 20,
  },
  {
    id: 'teach',
    name: 'Teach or explain',
    emoji: '🧑‍🏫',
    category: 'mind',
    blurb: 'You do not know it until you can hand it to someone else.',
    unit: 'minutes',
    xpPerUnit: 0.85,
    attributes: { knowledge: 0.5, relationships: 0.3, creativity: 0.2 },
    vitals: { spirit: 0.15, clarity: -0.05 },
    keyVital: 'clarity',
    softCap: 60,
    masteryStep: 240,
    tags: ['learning', 'social'],
    quickAmount: 15,
  },

  /* --------------------------------------------------------------- body */
  {
    id: 'water',
    name: 'Glass of water',
    emoji: '💧',
    category: 'body',
    blurb: 'The smallest possible good decision.',
    unit: 'glasses',
    xpPerUnit: 3,
    attributes: { health: 0.6 },
    vitals: { energy: 2.5, clarity: 1.5 },
    keyVital: 'energy',
    softCap: 8,
    masteryStep: 200,
    tags: ['wellness', 'quick'],
    quickAmount: 1,
    restores: 0.15,
  },
  {
    id: 'meal',
    name: 'Nourishing meal',
    emoji: '🍲',
    category: 'body',
    blurb: 'Food that was actually food.',
    unit: 'count',
    xpPerUnit: 9,
    attributes: { health: 0.9 },
    vitals: { energy: 9, spirit: 2 },
    keyVital: 'energy',
    softCap: 3,
    masteryStep: 90,
    tags: ['wellness'],
    quickAmount: 1,
    restores: 0.8,
  },
  {
    id: 'sleep',
    name: 'Sleep',
    emoji: '🌙',
    category: 'body',
    blurb: 'The single highest-leverage thing on this list.',
    unit: 'hours',
    xpPerUnit: 5,
    attributes: { health: 1.0, discipline: 0.25 },
    vitals: {},
    keyVital: 'energy',
    softCap: 9,
    masteryStep: 120,
    tags: ['wellness', 'rest'],
    quickAmount: 7.5,
    restores: 4,
  },
  {
    id: 'exercise',
    name: 'Workout',
    emoji: '🏋️',
    category: 'body',
    blurb: 'Lift, run, swim — anything that costs you something.',
    unit: 'minutes',
    xpPerUnit: 0.62,
    attributes: { fitness: 0.65, health: 0.3, discipline: 0.25 },
    vitals: { energy: 0.06, spirit: 0.12 },
    keyVital: 'energy',
    softCap: 90,
    masteryStep: 500,
    tags: ['movement'],
    quickAmount: 40,
    restores: 0.06,
    strain: 0.04,
  },
  {
    id: 'walk',
    name: 'Walk',
    emoji: '🚶',
    category: 'body',
    blurb: 'Underrated. Fixes more than it should.',
    unit: 'minutes',
    xpPerUnit: 0.34,
    attributes: { fitness: 0.3, health: 0.3, focus: 0.12 },
    vitals: { energy: 0.05, clarity: 0.12, spirit: 0.06 },
    keyVital: 'energy',
    softCap: 90,
    masteryStep: 600,
    tags: ['movement', 'calm'],
    quickAmount: 20,
    restores: 0.03,
  },
  {
    id: 'sport',
    name: 'Play a sport',
    emoji: '⚽',
    category: 'body',
    blurb: 'Movement that does not feel like exercise.',
    unit: 'minutes',
    xpPerUnit: 0.52,
    attributes: { fitness: 0.5, health: 0.2, relationships: 0.25 },
    vitals: { spirit: 0.18, energy: -0.02 },
    keyVital: 'energy',
    softCap: 120,
    masteryStep: 400,
    tags: ['movement', 'social'],
    quickAmount: 60,
    strain: 0.03,
  },
  {
    id: 'stretch',
    name: 'Stretch & mobility',
    emoji: '🧘',
    category: 'body',
    blurb: 'Ten minutes now, or a bad back later.',
    unit: 'minutes',
    xpPerUnit: 0.45,
    attributes: { fitness: 0.28, health: 0.35 },
    vitals: { energy: 0.08, clarity: 0.08 },
    keyVital: 'energy',
    softCap: 30,
    masteryStep: 200,
    tags: ['movement', 'calm', 'quick'],
    quickAmount: 10,
    restores: 0.06,
  },
  {
    id: 'rest',
    name: 'Deliberate rest',
    emoji: '☕',
    category: 'body',
    blurb: 'Chosen rest is not the same as collapse. It counts.',
    unit: 'minutes',
    xpPerUnit: 0.2,
    attributes: { health: 0.25 },
    vitals: { energy: 0.18, clarity: 0.1 },
    keyVital: 'energy',
    softCap: 45,
    masteryStep: 300,
    tags: ['wellness', 'rest', 'calm'],
    quickAmount: 20,
    restores: 0.05,
  },

  /* -------------------------------------------------------------- spirit */
  {
    id: 'quran',
    name: 'Read Qur’an',
    emoji: '🕌',
    category: 'spirit',
    blurb: 'Pages read, slowly.',
    unit: 'pages',
    xpPerUnit: 6,
    attributes: { spirituality: 1.0, knowledge: 0.25, focus: 0.2 },
    vitals: { spirit: 5, clarity: 1.5 },
    keyVital: 'spirit',
    softCap: 20,
    masteryStep: 604,
    tags: ['worship', 'calm'],
    quickAmount: 2,
    restores: 0.2,
  },
  {
    id: 'prayer',
    name: 'Prayer',
    emoji: '🤲',
    category: 'spirit',
    blurb: 'Kept, on time.',
    unit: 'count',
    xpPerUnit: 7,
    attributes: { spirituality: 0.85, discipline: 0.45, focus: 0.2 },
    vitals: { spirit: 5, clarity: 2 },
    keyVital: 'spirit',
    softCap: 5,
    masteryStep: 300,
    tags: ['worship', 'quick'],
    quickAmount: 1,
    restores: 0.3,
  },
  {
    id: 'dhikr',
    name: 'Dhikr',
    emoji: '📿',
    category: 'spirit',
    blurb: 'Remembrance, in the gaps of the day.',
    unit: 'minutes',
    xpPerUnit: 0.7,
    attributes: { spirituality: 0.7, focus: 0.3 },
    vitals: { spirit: 0.35, clarity: 0.15 },
    keyVital: 'spirit',
    softCap: 30,
    masteryStep: 300,
    tags: ['worship', 'calm', 'quick'],
    quickAmount: 10,
    restores: 0.04,
  },
  {
    id: 'reflect',
    name: 'Reflect & journal',
    emoji: '🪶',
    category: 'spirit',
    blurb: 'Write down what actually happened and how you felt about it.',
    unit: 'minutes',
    xpPerUnit: 0.62,
    attributes: { spirituality: 0.3, creativity: 0.25, organization: 0.2, focus: 0.2 },
    vitals: { spirit: 0.25, clarity: 0.2 },
    keyVital: 'spirit',
    softCap: 30,
    masteryStep: 240,
    tags: ['calm', 'reflection'],
    quickAmount: 10,
    restores: 0.05,
  },
  {
    id: 'meditate',
    name: 'Stillness',
    emoji: '🌌',
    category: 'spirit',
    blurb: 'Sit and breathe and do nothing else.',
    unit: 'minutes',
    xpPerUnit: 0.65,
    attributes: { focus: 0.6, health: 0.2, spirituality: 0.25 },
    vitals: { clarity: 0.45, spirit: 0.2 },
    keyVital: 'spirit',
    softCap: 30,
    masteryStep: 240,
    tags: ['calm', 'reflection'],
    quickAmount: 10,
    restores: 0.08,
  },
  {
    id: 'gratitude',
    name: 'Gratitude note',
    emoji: '🌾',
    category: 'spirit',
    blurb: 'One specific thing. Not a general feeling.',
    unit: 'count',
    xpPerUnit: 6,
    attributes: { spirituality: 0.5, relationships: 0.25 },
    vitals: { spirit: 6 },
    keyVital: 'spirit',
    softCap: 3,
    masteryStep: 100,
    tags: ['reflection', 'quick'],
    quickAmount: 1,
    restores: 0.2,
  },

  /* --------------------------------------------------------------- craft */
  {
    id: 'create',
    name: 'Creative work',
    emoji: '🎨',
    category: 'craft',
    blurb: 'Write, draw, compose, film. Make the thing.',
    unit: 'minutes',
    xpPerUnit: 0.62,
    attributes: { creativity: 0.7, focus: 0.2 },
    vitals: { spirit: 0.2, clarity: -0.06 },
    keyVital: 'clarity',
    softCap: 120,
    masteryStep: 500,
    tags: ['making', 'deep'],
    quickAmount: 30,
  },
  {
    id: 'build',
    name: 'Build something',
    emoji: '🛠️',
    category: 'craft',
    blurb: 'Code, repair, assemble, cook something ambitious.',
    unit: 'minutes',
    xpPerUnit: 0.66,
    attributes: { creativity: 0.45, knowledge: 0.3, focus: 0.25 },
    vitals: { spirit: 0.18, clarity: -0.08 },
    keyVital: 'clarity',
    softCap: 150,
    masteryStep: 600,
    tags: ['making', 'deep'],
    quickAmount: 45,
    strain: 0.01,
  },
  {
    id: 'skill',
    name: 'Deliberate practice',
    emoji: '🎻',
    category: 'craft',
    blurb: 'An instrument, a craft, a skill — practised badly on purpose until it is not.',
    unit: 'minutes',
    xpPerUnit: 0.68,
    attributes: { creativity: 0.35, discipline: 0.3, focus: 0.25 },
    vitals: { spirit: 0.12, clarity: -0.05 },
    keyVital: 'clarity',
    softCap: 60,
    masteryStep: 300,
    tags: ['making', 'deep'],
    quickAmount: 25,
  },

  /* --------------------------------------------------------------- order */
  {
    id: 'plan',
    name: 'Plan the day',
    emoji: '🗒️',
    category: 'order',
    blurb: 'Five minutes that buy back an hour.',
    unit: 'count',
    xpPerUnit: 11,
    attributes: { organization: 0.9, discipline: 0.4, focus: 0.3 },
    vitals: { clarity: 7 },
    keyVital: 'clarity',
    softCap: 1,
    masteryStep: 60,
    tags: ['order', 'quick'],
    quickAmount: 1,
  },
  {
    id: 'tidy',
    name: 'Tidy your space',
    emoji: '🧹',
    category: 'order',
    blurb: 'Outside matches inside, both directions.',
    unit: 'minutes',
    xpPerUnit: 0.42,
    attributes: { organization: 0.6, health: 0.15 },
    vitals: { clarity: 0.15 },
    keyVital: 'energy',
    softCap: 45,
    masteryStep: 300,
    tags: ['order'],
    quickAmount: 15,
  },
  {
    id: 'admin',
    name: 'Handle admin',
    emoji: '📮',
    category: 'order',
    blurb: 'The thing you have been avoiding for eleven days.',
    unit: 'minutes',
    xpPerUnit: 0.48,
    attributes: { organization: 0.55, discipline: 0.35 },
    vitals: { clarity: 0.1, spirit: 0.08 },
    keyVital: 'clarity',
    softCap: 45,
    masteryStep: 200,
    tags: ['order'],
    quickAmount: 20,
  },
  {
    id: 'finance',
    name: 'Review finances',
    emoji: '🪙',
    category: 'order',
    blurb: 'Look at the numbers, even when you would rather not.',
    unit: 'count',
    xpPerUnit: 12,
    attributes: { organization: 0.7, discipline: 0.3, knowledge: 0.15 },
    vitals: { clarity: 3 },
    keyVital: 'clarity',
    softCap: 1,
    masteryStep: 24,
    tags: ['order'],
    quickAmount: 1,
  },

  /* --------------------------------------------------------------- bonds */
  {
    id: 'family',
    name: 'Time with family',
    emoji: '🏡',
    category: 'bonds',
    blurb: 'Present, phone away.',
    unit: 'minutes',
    xpPerUnit: 0.48,
    attributes: { relationships: 0.7, spirituality: 0.15 },
    vitals: { spirit: 0.3 },
    keyVital: 'spirit',
    softCap: 120,
    masteryStep: 600,
    tags: ['social'],
    quickAmount: 45,
    restores: 0.03,
  },
  {
    id: 'friend',
    name: 'See a friend',
    emoji: '🫂',
    category: 'bonds',
    blurb: 'The friendships that last are the ones that get scheduled.',
    unit: 'minutes',
    xpPerUnit: 0.48,
    attributes: { relationships: 0.65, creativity: 0.1 },
    vitals: { spirit: 0.3 },
    keyVital: 'spirit',
    softCap: 120,
    masteryStep: 400,
    tags: ['social'],
    quickAmount: 60,
    restores: 0.03,
  },
  {
    id: 'call',
    name: 'Reach out',
    emoji: '📞',
    category: 'bonds',
    blurb: 'A real message to a real person.',
    unit: 'count',
    xpPerUnit: 7,
    attributes: { relationships: 0.55 },
    vitals: { spirit: 4 },
    keyVital: 'spirit',
    softCap: 3,
    masteryStep: 100,
    tags: ['social', 'quick'],
    quickAmount: 1,
  },
  {
    id: 'kindness',
    name: 'Act of kindness',
    emoji: '🤍',
    category: 'bonds',
    blurb: 'Something for someone who cannot repay it.',
    unit: 'count',
    xpPerUnit: 11,
    attributes: { relationships: 0.6, spirituality: 0.55 },
    vitals: { spirit: 8 },
    keyVital: 'spirit',
    softCap: 2,
    masteryStep: 80,
    tags: ['social', 'worship'],
    quickAmount: 1,
    restores: 0.3,
  },

  /* ------------------------------------------------------------- resolve */
  {
    id: 'early_rise',
    name: 'Woke early',
    emoji: '🌅',
    category: 'resolve',
    blurb: 'The day starts on your terms.',
    unit: 'count',
    xpPerUnit: 13,
    attributes: { discipline: 0.8, health: 0.25 },
    vitals: { clarity: 5, spirit: 3 },
    keyVital: 'energy',
    softCap: 1,
    masteryStep: 60,
    tags: ['restraint', 'quick'],
    quickAmount: 1,
  },
  {
    id: 'screen_free',
    name: 'Screen-free hour',
    emoji: '🌘',
    category: 'resolve',
    blurb: 'An hour the feed did not get.',
    unit: 'count',
    xpPerUnit: 10,
    attributes: { discipline: 0.75, focus: 0.55 },
    vitals: { clarity: 8, spirit: 2 },
    keyVital: 'clarity',
    softCap: 3,
    masteryStep: 100,
    tags: ['restraint'],
    quickAmount: 1,
    restores: 0.2,
  },
  {
    id: 'sleep_ontime',
    name: 'Slept on time',
    emoji: '🛏️',
    category: 'resolve',
    blurb: 'Tomorrow began the moment you closed the laptop.',
    unit: 'count',
    xpPerUnit: 11,
    attributes: { discipline: 0.65, health: 0.45 },
    vitals: {},
    keyVital: 'energy',
    softCap: 1,
    masteryStep: 60,
    tags: ['restraint', 'rest', 'quick'],
    quickAmount: 1,
    restores: 3,
  },

  /* --------------------------------------------------------------- hobbies
   *
   * These exist because "creative work" is not a thing anyone actually does.
   * People bake, or crochet, or paint — and each one asks something different
   * of you, so each one is worth something different. Crochet and painting
   * both cost creativity, but only one of them calms you down.
   */
  {
    id: 'bake',
    name: 'Baking',
    emoji: '🧁',
    category: 'craft',
    blurb: 'A recipe is a promise you make to someone, usually including yourself.',
    unit: 'minutes',
    // Precision work that ends in something to give away — it pays across
    // creativity, care and the discipline of actually following the method.
    xpPerUnit: 0.64,
    attributes: { creativity: 0.42, relationships: 0.2, discipline: 0.18, organization: 0.1 },
    vitals: { spirit: 0.22, energy: -0.04 },
    keyVital: 'energy',
    softCap: 120,
    masteryStep: 400,
    tags: ['making', 'home', 'calm'],
    quickAmount: 45,
  },
  {
    id: 'crochet',
    name: 'Crochet',
    emoji: '🧶',
    category: 'craft',
    blurb: 'Rows that add up while your mind goes quiet.',
    unit: 'minutes',
    // The rare making that restores instead of spending. Almost nothing else
    // in the catalogue gives clarity back while you do it.
    xpPerUnit: 0.55,
    attributes: { creativity: 0.4, focus: 0.22, discipline: 0.16 },
    vitals: { spirit: 0.2, clarity: 0.1 },
    keyVital: 'spirit',
    softCap: 150,
    masteryStep: 500,
    tags: ['making', 'calm', 'handwork'],
    quickAmount: 30,
    restores: 0.02,
  },
  {
    id: 'paint',
    name: 'Painting',
    emoji: '🖌️',
    category: 'craft',
    blurb: 'The one that is allowed to go badly.',
    unit: 'minutes',
    xpPerUnit: 0.66,
    attributes: { creativity: 0.72, focus: 0.18 },
    vitals: { spirit: 0.26, clarity: -0.05 },
    keyVital: 'spirit',
    softCap: 120,
    masteryStep: 450,
    tags: ['making', 'deep', 'expressive'],
    quickAmount: 40,
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    emoji: '🔢',
    category: 'mind',
    blurb: 'A small closed world with exactly one right answer in it.',
    unit: 'minutes',
    // Pure focus training. Short soft cap on purpose: this is a sharpener,
    // and an hour of it is not three times better than twenty minutes.
    xpPerUnit: 0.5,
    attributes: { focus: 0.55, discipline: 0.18, knowledge: 0.1 },
    vitals: { clarity: 0.04 },
    keyVital: 'clarity',
    softCap: 45,
    masteryStep: 250,
    tags: ['puzzle', 'calm', 'sharp'],
    quickAmount: 20,
  },
  {
    id: 'game',
    name: 'Playing a game',
    emoji: '🎮',
    category: 'craft',
    blurb: 'Rest that you are awake for. It counts — it was never wasted time.',
    unit: 'minutes',
    // Deliberately a real action with real value. An app that scores your life
    // and quietly rates your rest at zero is lying about how people work.
    xpPerUnit: 0.34,
    attributes: { creativity: 0.2, focus: 0.16, relationships: 0.06 },
    vitals: { spirit: 0.18, energy: 0.04 },
    keyVital: 'spirit',
    softCap: 120,
    masteryStep: 600,
    tags: ['play', 'rest'],
    quickAmount: 45,
    restores: 0.01,
  },
];

export const ACTIONS: Record<string, ActionDef> = Object.fromEntries(defs.map((a) => [a.id, a]));
export const ACTION_LIST: ActionDef[] = defs;
export const ACTION_IDS = defs.map((a) => a.id);

export function getAction(id: string): ActionDef | undefined {
  return ACTIONS[id];
}

/** Sensible starting rituals — the anchors of a complete day. */
export const DEFAULT_RITUALS = ['prayer', 'quran', 'water', 'study', 'walk', 'sleep'];

/** Mastery tier thresholds as multiples of an action's `masteryStep`. */
export const MASTERY_MULTIPLES = [1, 3, 7, 15, 31];
export const MASTERY_NAMES = ['Novice', 'Practised', 'Adept', 'Expert', 'Master', 'Lifelong'];
